DROP DATABASE IF EXISTS Api_rest;
CREATE DATABASE IF NOT EXISTS Api_rest;
USE Api_rest;

DROP TABLE IF EXISTS usuario;

CREATE TABLE IF NOT EXISTS usuario(
    id INT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
    nome VARCHAR(255) NOT NULL,
    email VARCHAR(255) UNIQUE,
    senha VARCHAR(255) NOT NULL
);
